name: 04 - Using Actions

on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

    #0. Checkout the code from the repository
    #1. Install deps of our react application
    #2. Execute an automated tests
