name: 04 - Using Actions

on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci

    #0. Checkout the code from the repository
    #1. Install deps of our react application
    #2. Execute an automated tests
